services:
  - type: web
    name: binance-bob-usdt-proxy
    env: node
    rootDir: proxy-server
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: PORT
        value: 10000
