services:
  - type: web
    name: binance-bob-usdt-proxy
    env: node
    runtime: node
    nodeVersion: 18
    buildCommand: cd /opt/render/project/src/proxy-server && npm install
    startCommand: node /opt/render/project/src/proxy-server/server.js
    envVars:
      - key: PORT
        value: 10000
