services:
  - type: web
    name: binance-bob-usdt-proxy
    env: node
    runtime: node
    nodeVersion: 18
    buildCommand: cd proxy-server && npm install
    startCommand: cd proxy-server && npm start
    envVars:
      - key: PORT
        value: 10000
