services:
  - type: web
    name: binance-bob-usdt-proxy
    env: node
    buildCommand: cd proxy-server && npm install
    startCommand: cd proxy-server && node server.js
    envVars:
      - key: PORT
        value: 10000
